### ISSUE TITLE
Mobs are invinsible once you die

### ISSUE THREAD

**Issue by WildLady99** [JadedPacks/AS2Configs#37]
I died on the cottage island and the mobs that had spawned were not able to be attacked. New mobs could be attacked but both could hurt the player. There didn't seem to be any hit box and both zombies and skeletons could attack. I did not confirm with other mobs because I just kept getting killed at the spawn area. 
Version 1.1.14 on the Twitch (was curse) launcher

**Comment by Developaws** [comment]
Fixed in upstream.
