### ISSUE TITLE
Questbook not 100% completable. 

### ISSUE THREAD

**Issue by cstdenis** [JadedPacks/AS2Configs#43]
Even after completing all available quests, some categories do not show 100%. For example For the Hording only show 92%, with 0 available for completion. 

Based on your wiki, it looks like these are what is missing in that category

https://jadedpacks.gamepedia.com/Agrarian_Skies_2:Hoarders
https://jadedpacks.gamepedia.com/Agrarian_Skies_2:Infinite_Storage_(For_the_Hoarding)

There does not appear to be any way to make them available, even after completing The Ultimate Quest.

**Comment by Developaws** [comment]
Fixed in upstream.
