### ISSUE TITLE
Recall stones not rechargable

### ISSUE THREAD

**Issue by Developaws** [JadedPacks/AS2Configs#7]
_From @andyb2 on October 27, 2015 1:8_

I've had this issue for a few releases.The recall stones do nothing when in the crafting table with ender pearls. I asked vanhal about this issue and he tested it but the mod is fine so he thinks it has something to do with the recipe being changed.

_Copied from original issue: jadedcat/AS2Configs#157_

**Comment by Developaws** [comment]
_From @pjfranke on December 14, 2015 6:13_

This is a known issue, that as you say has persisted for a few updates.  No fix has been found yet, so unfortunately for now the recall stones are not rechargeable.

**Comment by Ace1362** [comment]
Have you found any solution? I find that the recall stones original recipe is functioning aside from the not recharging part

**Comment by Ace1362** [comment]
I have used this indivdual mod many times and it appears to be functional entirely by vanilla recipes aside from the recharge

**Comment by Developaws** [comment]
Fixed in upstream.
