### ISSUE TITLE
Cooking for Blockheads

### ISSUE THREAD

**Issue by Developaws** [JadedPacks/AS2Configs#9]
_From @flirtyflashr on November 7, 2015 19:53_

On Version 1.1.14 When I open Cooking for Blockheads (no numberal), the cookbook where the tooltip is saying it'll show all the recipes. It crashes.

_Copied from original issue: jadedcat/AS2Configs#166_

**Comment by Developaws** [comment]
_From @Trisscar05 on November 9, 2015 7:32_

Do you have a crash log, and if so could you post it please?

**Comment by Developaws** [comment]
_From @flirtyflashr on November 9, 2015 22:9_

Curse\Minecraft\Instances\Agrarian Skies 2\crash-reports

is empty.

and appdata roaming .minecraft isnt there any more, It was there before but i cant remember what i did... im guessing that i had some problems with minecraft once, and then wanted to reinstall, so i deleted that folder

**Comment by Developaws** [comment]
_From @shadowfacts on November 9, 2015 22:20_

Can you send the FML log? It'll be in `Curse\Minecraft\Instances\Agrarian Skies 2\logs\fml-client-latest.log`

**Comment by Developaws** [comment]
_From @flirtyflashr on November 9, 2015 22:45_

I am playing on a server i run locally btw,, dont know if that matters.

So what i have done is, restarted server, restarted client, logging in. Opened that cookbook, and then it says error occured, bringing you back to title screen.

https://drive.google.com/file/d/0B844Xdn3prnzWEo4cDFjY1RXanM/view?usp=sharing

**Comment by Developaws** [comment]
_From @Chronoman17 on November 29, 2015 0:8_

I can confirm this issue.  I run Single Player, but upon right-clicking on the Cooking Table, the game crashed.  I tried taking some food out of the fridge, and it seemed that once I removed the Stock (which is an ingredient in a substantial number of recipes), it was behaving properly.  When the Stock re-entered the fridge or my own inventory, the game crashed.  It seems that the crash relates to either a certain recipe that uses Stock, or having a ton of recipes to display, but I can't be sure.  Also on 1.1.14

FML Crash Log: https://gist.github.com/Chronoman17/e475533b479057e4e04b

**Comment by Developaws** [comment]
_From @pson on March 26, 2016 9:32_

I had this but with a totally empty fridge. I added the above mentioned FML file as well, please tell me if there is anything else I can do.

https://drive.google.com/file/d/0B9J4VhgTgPX9RnpCSjVvVUpvcXM/view?usp=sharing

**Comment by Developaws** [comment]
_From @Trisscar05 on March 26, 2016 19:43_

Use NEI instead of the book, and if you can't get back into your world or near the chunk where it sits, use MCEdit to delete the fridge block. Otherwise wait till the mod author or the pack creator sorts it out I'm afraid.

**Comment by Developaws** [comment]
_From @pson on March 27, 2016 11:12_

It's not a problem, I didn't use it much (just played with it since it's a cool thing) and it only crashed when I try to right-click the cooking table, so it does not cause me any trouble, This whole thing is to provide what assistance I can when you're searching for the bug.

**Comment by Developaws** [comment]
_From @Moojuiceman on May 23, 2016 22:35_

**Seed soup** is the issue. Uses stock and any compatible seed. Same crash happens when using 'Cooking for blockheads I' with the items in your inventory (or fridge). Seems the UI can't display it properly and crashes.

**Comment by Developaws** [comment]
Fixed in upstream.

**Comment by pson** [comment]
Thank you
